version: '3.8'

services:
  homepage-config:
    image: thsrite/homepage-config:latest
    container_name: homepage-config
    restart: unless-stopped
    ports:
      - "9835:9835"
    volumes:
      # Mount config directory to persist configuration
      - ./homepage/services.yaml:/app/config/services.yaml
      - ./homepage/bookmarks.yaml:/app/config/bookmarks.yaml
      # Mount images directory for custom icons (change the host path as needed)
      - /volume1/docker/homepage/image:/app/public/images
    environment:
      # Required: Authentication credentials
      - AUTH_USERNAME=admin  # Change this!
      - AUTH_PASSWORD=admin  # Change this!
      # Optional: Session secret (change for production)
      - SESSION_SECRET=change-this-to-a-random-secret-key
      # Optional: Session expiration in minutes (default: 1440 = 24 hours)
      - SESSION_EXPIRE_MINUTES=1440
      # Optional: Override port if needed
      - PORT=9835
      # Optional: Set debug mode
      - DEBUG=false
    labels:
      - "com.docker.description=Homepage Configuration Tool"
      - "com.docker.project=homepage-config"
    networks:
      - homepage-network

networks:
  homepage-network:
    driver: bridge
    name: homepage-network